// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wckvacujxrgpcxxhgzzc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indja3ZhY3VqeHJncGN4eGhnenpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MDU2NDEsImV4cCI6MjA2NDA4MTY0MX0.5dFNNNHcjI0uVkyGLGtjyXaDPWomwZYins1Hknib5Z8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);